# Generated by Django 4.0.2 on 2022-02-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='voter',
        ),
    ]
