# Generated by Django 4.0.2 on 2022-02-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_vote_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='questions', to='voting.Option'),
        ),
    ]
