# Generated by Django 4.0.2 on 2022-02-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_question_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
